services:
  - type: web
    name: noo-tv
    runtime: node
    plan: free
    buildCommand: npm install && npx playwright install --with-deps chromium && npm run build
    startCommand: npm start -- -p $PORT
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
