services:
  - type: web
    name: noo-tv-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx playwright install --with-deps chromium && npm run build
    startCommand: npm start -- -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
